[package]
name = "synerex_nodeapi"
version = "0.5.0"
edition = "2021"

[build-dependencies]
git2 = "0.17.2"
protobuf-codegen = "3.2.0"
protoc-bin-vendored = "3.0.0"
tonic-build = "0.10.0"

[dependencies]
prost = "0.12.1"
prost-types = "0.12.1"
tonic = "0.10.0"
